# Generated by Django 4.2.5 on 2023-09-15 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepg', '0003_alumni'),
    ]

    operations = [
        migrations.CreateModel(
            name='Homepage_intro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('homepage_thuziak', models.TextField()),
            ],
        ),
    ]
