# Generated by Django 4.2.5 on 2023-09-16 08:24

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepg', '0004_homepage_intro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumni',
            name='thuziak',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='homepage_intro',
            name='homepage_thuziak',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
