# Generated by Django 4.2.5 on 2023-09-17 18:09

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepg', '0005_alter_alumni_thuziak_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumni',
            name='thuziak_readmore',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
