# Generated by Django 4.2.5 on 2023-09-17 18:12

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepg', '0006_alumni_thuziak_readmore'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumni',
            name='thuziak_readmore',
        ),
        migrations.AddField(
            model_name='homepage_intro',
            name='thuziak_readmore',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
