# Generated by Django 4.2.5 on 2023-09-19 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepg', '0007_remove_alumni_thuziak_readmore_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cons_titution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('constitution_pdf', models.FileField(upload_to='')),
            ],
        ),
    ]
