# Generated by Django 4.2.5 on 2023-09-19 19:01

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepg', '0008_cons_titution'),
    ]

    operations = [
        migrations.AddField(
            model_name='cons_titution',
            name='constitution_word',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
