# Generated by Django 4.2.5 on 2023-09-20 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepg', '0010_syllabus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Previous_Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(max_length=50)),
                ('link2', models.CharField(max_length=700)),
            ],
        ),
        migrations.AddField(
            model_name='syllabus',
            name='branch',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
