# Generated by Django 4.2.5 on 2023-09-20 18:46

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepg', '0011_previous_question_syllabus_branch'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_word', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('notice_photo', models.FileField(upload_to='')),
            ],
        ),
    ]
