# Generated by Django 4.2.5 on 2023-09-25 18:00

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepg', '0014_placement_resume'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee_word', ckeditor.fields.RichTextField(blank=True, null=True)),
            ],
        ),
    ]
