# Generated by Django 4.2.5 on 2023-09-25 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepg', '0015_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='fee',
            name='desig_alumni',
            field=models.CharField(max_length=700, null=True),
        ),
        migrations.AddField(
            model_name='fee',
            name='img_alumni',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='fee',
            name='name_alumni',
            field=models.CharField(max_length=700, null=True),
        ),
    ]
