# Generated by Django 4.2.5 on 2023-09-25 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepg', '0016_fee_desig_alumni_fee_img_alumni_fee_name_alumni'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fee',
            name='desig_alumni',
        ),
        migrations.RemoveField(
            model_name='fee',
            name='img_alumni',
        ),
        migrations.RemoveField(
            model_name='fee',
            name='name_alumni',
        ),
        migrations.AddField(
            model_name='alumni',
            name='desig_alumni',
            field=models.CharField(max_length=700, null=True),
        ),
        migrations.AddField(
            model_name='alumni',
            name='img_alumni',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='alumni',
            name='name_alumni',
            field=models.CharField(max_length=700, null=True),
        ),
    ]
