# Generated by Django 4.2.5 on 2023-09-26 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepg', '0017_remove_fee_desig_alumni_remove_fee_img_alumni_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cons_titution',
            new_name='About',
        ),
    ]
