# Generated by Django 4.2.5 on 2023-09-26 16:56

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepg', '0018_rename_cons_titution_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thuziak_blog', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('name_blog', models.CharField(max_length=700, null=True)),
                ('year_batch', models.CharField(max_length=700, null=True)),
                ('img_blog', models.FileField(null=True, upload_to='')),
            ],
        ),
    ]
