# Generated by Django 4.2.5 on 2023-09-29 11:52

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepg', '0019_blog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scholarship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thuziak_scho', ckeditor.fields.RichTextField(blank=True, null=True)),
            ],
        ),
    ]
