# Generated by Django 4.2.5 on 2023-09-29 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepg', '0020_scholarship'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=700)),
                ('branch', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
