# Generated by Django 4.2.5 on 2023-09-29 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepg', '0021_material'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gallery_image', models.FileField(null=True, upload_to='')),
            ],
        ),
    ]
