# Generated by Django 4.2.5 on 2023-09-29 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepg', '0022_gallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='description',
            field=models.CharField(max_length=700, null=True),
        ),
    ]
